version: '2.1'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=concepttoclinic

  interface:
    build:
      context: .
      dockerfile: ./compose/interface/Dockerfile-dev-api
    command: /start-dev.sh
    depends_on:
      - postgres
      - prediction
    environment:
      - POSTGRES_USER=concepttoclinic
      - USE_DOCKER=yes
      - SECRET_KEY=notverysecret
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - ./interface/:/app
      - ./tests/assets/test_image_data/small:/images
      - ./.git/logs/HEAD:/HEAD
      - ./prediction/src/algorithms/classify/assets/:/classify_models
    ports:
      - "8000:8000"

  vue:
    build:
      context: .
      dockerfile: ./compose/interface/Dockerfile-dev-vue
    command: npm run dev
    depends_on:
      - interface
    volumes:
      - ./interface/frontend/src:/app/src
      - ./interface/frontend/build:/app/build
      - ./interface/frontend/config:/app/config
      - ./interface/frontend/dist:/app/dist
      - ./interface/frontend/static:/app/static
      - ./interface/frontend/test:/app/test
      - ./.git/logs/HEAD:/HEAD
    links:
      - interface
    ports:
      - "8080:8080"

  prediction:
    build:
      context: .
      dockerfile: ./compose/prediction/Dockerfile-dev
    command: flask run --host=0.0.0.0 --port=8001
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=src/factory.py
    volumes:
      - ./prediction/:/app
      - ./tests/assets/test_image_data/small:/images
      - ./prediction/src/algorithms/classify/assets/:/classify_models
    ports:
      - "8001:8001"
